import Link from "next/link";
import { getCurrentOrgId, getCurrentPerson, requireSession } from "@/lib/session";
import { prisma } from "@/lib/db";
import { acceptRoleNominationAction, nominateRoleApplicationAction, submitRoleAssignmentToGovernance } from "./actions";

export const dynamic = "force-dynamic";

export default async function RoleApplicationsPage() {
  const session = await requireSession();
  const organizationId = await getCurrentOrgId();
  const person = await getCurrentPerson();
  if (!person) return <div className="mx-auto max-w-3xl p-8 text-sm text-muted-foreground">当前账号没有组织内人员身份。</div>;
  const membership = await prisma.membership.findUnique({ where: { userId_organizationId: { userId: session.user.id, organizationId } }, select: { role: true } });
  if (!membership) return <div className="mx-auto max-w-3xl p-8 text-sm text-muted-foreground">当前账号不属于该组织。</div>;

  const [applications, meetings, tensions, people] = await Promise.all([prisma.roleAssignmentApplication.findMany({
    where: { organizationId, status: { in: ["PENDING", "NOMINATED"] } },
    include: { role: { select: { id: true, name: true, circle: { select: { name: true } } } }, applicant: { select: { name: true, email: true } } },
    orderBy: [{ createdAt: "asc" }, { id: "asc" }],
  }), prisma.meeting.findMany({ where: { organizationId, type: "GOVERNANCE", endedAt: null }, select: { id: true, title: true, startedAt: true }, orderBy: { startedAt: "asc" }, take: 10 }), prisma.tension.findMany({ where: { organizationId, status: "OPEN" }, select: { id: true, title: true }, orderBy: { createdAt: "asc" }, take: 20 }), prisma.person.findMany({ where: { organizationId, entityType: "HUMAN" }, select: { id: true, name: true, email: true }, orderBy: { name: "asc" }, take: 100 })]);

  return <div className="mx-auto max-w-5xl animate-fade-rise">
    <div className="mb-8"><Link href="/app/roles/market" className="text-sm text-moss hover:underline">← 返回角色市场</Link><p className="mb-1 mt-6 text-xs font-medium uppercase tracking-wider text-moss">角色治理</p><h1 className="font-serif text-2xl font-medium">任职申请收件箱</h1><p className="mt-2 text-sm text-muted-foreground">这里是待进入治理流程的申请证据。查看申请不等于任命，任职变化必须由相应会议流程确认。</p></div>
    {applications.length === 0 ? <div className="rounded-card border border-dashed border-border p-10 text-center text-sm text-muted-foreground">当前没有待处理申请。</div> : <div className="space-y-4">{applications.map((application) => <article key={application.id} className="rounded-card border border-border bg-card p-5 shadow-soft"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-medium">{application.role.name}</h2><p className="mt-1 text-xs text-muted-foreground">{application.role.circle.name} · {application.applicant.name} · {application.applicant.email}</p></div><span className="rounded-full bg-seed-pale px-2 py-1 text-[11px] text-seed">{application.status === "NOMINATED" ? "待本人接受提名" : "待治理确认"}</span></div><dl className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><dt className="text-xs text-muted-foreground">申请动机</dt><dd className="mt-1 whitespace-pre-wrap">{application.motivation}</dd></div><div><dt className="text-xs text-muted-foreground">相关能力</dt><dd className="mt-1 whitespace-pre-wrap">{application.capabilitySummary}</dd></div><div><dt className="text-xs text-muted-foreground">投入承诺</dt><dd className="mt-1 whitespace-pre-wrap">{application.commitment}</dd></div></dl>{application.status === "NOMINATED" && application.applicant.email === session.user.email ? <form action={acceptRoleNominationAction} className="mt-4 border-t border-border pt-3"><input type="hidden" name="applicationId" value={application.id} /><button type="submit" className="h-9 rounded-input bg-primary px-3 text-sm text-primary-foreground">接受提名并补充申请</button></form> : application.applicant.email === session.user.email ? <form action={submitRoleAssignmentToGovernance} className="mt-4 grid gap-2 border-t border-border pt-3 sm:grid-cols-3"><input type="hidden" name="applicationId" value={application.id} /><select name="meetingId" required className="h-9 border border-border bg-background px-2 text-sm"><option value="">选择治理会</option>{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{meeting.title}</option>)}</select><select name="tensionId" required className="h-9 border border-border bg-background px-2 text-sm"><option value="">选择来源张力</option>{tensions.map((tension) => <option key={tension.id} value={tension.id}>{tension.title}</option>)}</select><button type="submit" className="h-9 rounded-input bg-primary px-3 text-sm text-primary-foreground">提交治理审核</button></form> : <p className="mt-4 border-t border-border pt-3 text-xs text-muted-foreground">申请人需本人提交治理审核，其他人只能查看证据。</p>}<div className="mt-4 border-t border-border pt-3 text-xs text-muted-foreground">提交于 {application.createdAt.toLocaleDateString("zh-CN")} · 请在治理会议中形成确认议案</div></article>)}</div>}
    {membership.role === "ORG_ADMIN" ? <section className="mt-8 rounded-card border border-border bg-card p-5 shadow-soft"><h2 className="text-base font-medium">提名空缺角色</h2><p className="mt-1 text-sm text-muted-foreground">提名只产生候选记录，不会直接任命；被提名人接受后仍须经过治理会议确认。</p><form action={nominateRoleApplicationAction} className="mt-4 grid gap-2 md:grid-cols-3"><select name="roleId" required className="h-9 border border-border bg-background px-2 text-sm"><option value="">选择空缺角色</option>{(await prisma.roleDef.findMany({ where: { organizationId, status: "ACTIVE", assignees: { none: {} } }, select: { id: true, name: true }, orderBy: { name: "asc" } })).map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select><select name="nomineeId" required className="h-9 border border-border bg-background px-2 text-sm"><option value="">选择组织成员</option>{people.filter((candidate) => candidate.id !== person.id).map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}{candidate.email ? ` · ${candidate.email}` : ""}</option>)}</select><button type="submit" className="h-9 rounded-input bg-primary px-3 text-sm text-primary-foreground">提交提名</button></form></section> : null}
  </div>;
}
