module.exports = {
  apps: [
    {
      name: "csi-loopos-web",
      script: ".next/standalone/server.js",
      cwd: __dirname,
      exec_mode: "cluster",
      instances: "max",
      env: {
        NODE_ENV: "production",
        PORT: 3040,
        HOSTNAME: "127.0.0.1",
      },
      max_memory_restart: "1G",
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 15000,
      node_args: "--enable-source-maps",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      merge_logs: true,
    },
    {
      name: "csi-loopos-worker",
      script: "tsx",
      args: "worker/index.ts",
      cwd: __dirname,
      exec_mode: "fork",
      instances: 1,
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "512M",
      max_restarts: 10,
      min_uptime: "10s",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "./logs/worker-error.log",
      out_file: "./logs/worker-out.log",
      merge_logs: true,
    },
  ],
};
