import { buildReport, demoParticipant } from "./scoring";
import type { AssessmentAnswers, Report } from "./types";

const baseAnswers: AssessmentAnswers[] = [
  {
    stage_l1: "stable",
    stage_l2: "stable",
    stage_l3: "occasional",
    stage_l4: "not_yet",
    stage_l5: "not_yet",
    spiral_structure_1: 3,
    spiral_structure_2: 2,
    spiral_structure_3: 3,
    spiral_cell_1: 2,
    spiral_cell_2: 2,
    spiral_cell_3: 3,
    spiral_environment_1: 3,
    spiral_environment_2: 2,
    spiral_environment_3: 2,
    energy_meaning_1: 3,
    energy_meaning_2: 3,
    energy_meaning_3: 2,
    energy_power_1: 2,
    energy_power_2: 2,
    energy_power_3: 2,
    energy_trust_1: 3,
    energy_trust_2: 2,
    energy_trust_3: 2,
    chain_1: 4,
    chain_2: 3,
    chain_3: 3,
    chain_4: 2,
    chain_5: 2,
    charter_1: 2,
    charter_2: 2,
    charter_3: 2,
    charter_4: 3,
    charter_5: 2,
    open_scenario: "AI 帮大家写材料变快了，但流程、验收和责任没有改变。",
    open_workflow: "绩效反馈材料整理和管理者一对一辅导准备。",
    open_blocker: "主要来自权力和信任：试点团队没有调整流程的授权，也缺少复核机制。",
  },
  {
    stage_l1: "stable",
    stage_l2: "occasional",
    stage_l3: "not_yet",
    stage_l4: "not_yet",
    stage_l5: "not_yet",
    spiral_structure_1: 2,
    spiral_structure_2: 2,
    spiral_structure_3: 2,
    spiral_cell_1: 2,
    spiral_cell_2: 3,
    spiral_cell_3: 2,
    spiral_environment_1: 2,
    spiral_environment_2: 2,
    spiral_environment_3: 3,
    energy_meaning_1: 2,
    energy_meaning_2: 2,
    energy_meaning_3: 2,
    energy_power_1: 3,
    energy_power_2: 2,
    energy_power_3: 2,
    energy_trust_1: 2,
    energy_trust_2: 3,
    energy_trust_3: 2,
    chain_1: 3,
    chain_2: 2,
    chain_3: 3,
    chain_4: 2,
    chain_5: 2,
    charter_1: 2,
    charter_2: 3,
    charter_3: 2,
    charter_4: 2,
    charter_5: 2,
    open_scenario: "大家会用 AI 写 JD，但候选人画像和面试标准没有同步更新。",
    open_workflow: "招聘 JD 到候选人初筛。",
    open_blocker: "意义不清，业务部门只把它当成节省 HR 时间的工具。",
  },
  {
    stage_l1: "stable",
    stage_l2: "stable",
    stage_l3: "stable",
    stage_l4: "occasional",
    stage_l5: "not_yet",
    spiral_structure_1: 4,
    spiral_structure_2: 3,
    spiral_structure_3: 4,
    spiral_cell_1: 4,
    spiral_cell_2: 4,
    spiral_cell_3: 3,
    spiral_environment_1: 3,
    spiral_environment_2: 3,
    spiral_environment_3: 2,
    energy_meaning_1: 4,
    energy_meaning_2: 4,
    energy_meaning_3: 3,
    energy_power_1: 3,
    energy_power_2: 3,
    energy_power_3: 3,
    energy_trust_1: 2,
    energy_trust_2: 2,
    energy_trust_3: 2,
    chain_1: 4,
    chain_2: 4,
    chain_3: 3,
    chain_4: 4,
    chain_5: 3,
    charter_1: 2,
    charter_2: 2,
    charter_3: 2,
    charter_4: 3,
    charter_5: 2,
    open_scenario: "组织诊断访谈已经用 AI 辅助整理，但大家担心隐私和解释责任。",
    open_workflow: "组织诊断访谈纪要分析。",
    open_blocker: "信任不足，需要先补证据保留、人工复核和申诉机制。",
  },
];

export function demoReports(): Report[] {
  return baseAnswers.map((answers, index) =>
    buildReport("20260517-hr-od-workshop", { ...demoParticipant, displayName: `示例参与者 ${index + 1}` }, answers, `demo-${index + 1}`),
  );
}
