import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: "stage_l1",
    module: "stage",
    dimension: "L1",
    title: "每个关键部门至少有一个 AI 工具在日常工作中被实质性使用。",
    type: "stage",
    sortOrder: 1,
  },
  {
    id: "stage_l2",
    module: "stage",
    dimension: "L2",
    title: "至少有一个核心流程中，AI 输出已经进入标准工作流。",
    type: "stage",
    sortOrder: 2,
  },
  {
    id: "stage_l3",
    module: "stage",
    dimension: "L3",
    title: "至少有一个人机混合试点团队，且协作方式可以被第二个团队复用。",
    type: "stage",
    sortOrder: 3,
  },
  {
    id: "stage_l4",
    module: "stage",
    dimension: "L4",
    title: "公司层面已形成跨职能 AI 转型联盟，AI 项目验收标准从“工具使用”转向“业务结果”。",
    type: "stage",
    sortOrder: 4,
  },
  {
    id: "stage_l5",
    module: "stage",
    dimension: "L5",
    title: "团队中很少再把相关工作称为“AI 项目”，因为 AI 已经成为默认工作方式。",
    type: "stage",
    sortOrder: 5,
  },

  {
    id: "spiral_structure_1",
    module: "spiral",
    dimension: "structure",
    title: "新任务启动时，跨职能协作不需要长期依赖层层审批。",
    type: "scale",
    sortOrder: 10,
  },
  {
    id: "spiral_structure_2",
    module: "spiral",
    dimension: "structure",
    title: "核心业务链路能围绕价值流动，而不是被部门边界切碎。",
    type: "scale",
    sortOrder: 11,
  },
  {
    id: "spiral_structure_3",
    module: "spiral",
    dimension: "structure",
    title: "AI 项目能找到明确业务锚点，而不是停留在工具试用或技术展示。",
    type: "scale",
    sortOrder: 12,
  },
  {
    id: "spiral_cell_1",
    module: "spiral",
    dimension: "cell",
    title: "团队中已经出现人 + AI 的稳定任务单元。",
    type: "scale",
    sortOrder: 13,
  },
  {
    id: "spiral_cell_2",
    module: "spiral",
    dimension: "cell",
    title: "人负责什么、AI 负责什么、自动化负责什么，已经有明确分工。",
    type: "scale",
    sortOrder: 14,
  },
  {
    id: "spiral_cell_3",
    module: "spiral",
    dimension: "cell",
    title: "AI 输出有清晰验收标准，而不是依赖个人感觉判断好坏。",
    type: "scale",
    sortOrder: 15,
  },
  {
    id: "spiral_environment_1",
    module: "spiral",
    dimension: "environment",
    title: "员工能说清 AI 转型和自己当前工作的关系。",
    type: "scale",
    sortOrder: 16,
  },
  {
    id: "spiral_environment_2",
    module: "spiral",
    dimension: "environment",
    title: "管理者愿意为小范围试错提供权力、资源和容错空间。",
    type: "scale",
    sortOrder: 17,
  },
  {
    id: "spiral_environment_3",
    module: "spiral",
    dimension: "environment",
    title: "团队允许质疑 AI 输出，并能把错误沉淀为规则或清单。",
    type: "scale",
    sortOrder: 18,
  },

  {
    id: "energy_meaning_1",
    module: "energy",
    dimension: "meaning",
    title: "团队清楚为什么要在这个场景使用 AI，而不只是因为“大家都在用”。",
    type: "scale",
    sortOrder: 30,
  },
  {
    id: "energy_meaning_2",
    module: "energy",
    dimension: "meaning",
    title: "AI 项目和业务目标、用户价值或组织能力提升之间有明确连接。",
    type: "scale",
    sortOrder: 31,
  },
  {
    id: "energy_meaning_3",
    module: "energy",
    dimension: "meaning",
    title: "员工能看到 AI 使用带来的角色进化，而不是只看到被替代风险。",
    type: "scale",
    sortOrder: 32,
  },
  {
    id: "energy_power_1",
    module: "energy",
    dimension: "power",
    title: "负责 AI 试点的人拥有足够决策权，可以调整流程或资源。",
    type: "scale",
    sortOrder: 33,
  },
  {
    id: "energy_power_2",
    module: "energy",
    dimension: "power",
    title: "AI 项目的责任人清楚，成功或失败不会变成无人负责。",
    type: "scale",
    sortOrder: 34,
  },
  {
    id: "energy_power_3",
    module: "energy",
    dimension: "power",
    title: "试点团队知道哪些事情可以自主决定，哪些必须升级审批。",
    type: "scale",
    sortOrder: 35,
  },
  {
    id: "energy_trust_1",
    module: "energy",
    dimension: "trust",
    title: "AI 输出有可追溯记录和复核机制。",
    type: "scale",
    sortOrder: 36,
  },
  {
    id: "energy_trust_2",
    module: "energy",
    dimension: "trust",
    title: "跨部门协作有接口契约，减少反复确认和责任漂移。",
    type: "scale",
    sortOrder: 37,
  },
  {
    id: "energy_trust_3",
    module: "energy",
    dimension: "trust",
    title: "当 AI 出错时，团队倾向于复盘机制，而不是简单追责某个人。",
    type: "scale",
    sortOrder: 38,
  },

  {
    id: "chain_1",
    module: "chain",
    title: "我们能选出一条 7-30 天内可试跑的真实工作流。",
    type: "scale",
    sortOrder: 50,
  },
  {
    id: "chain_2",
    module: "chain",
    title: "这条工作流有明确输入、输出和验收标准。",
    type: "scale",
    sortOrder: 51,
  },
  {
    id: "chain_3",
    module: "chain",
    title: "这条工作流允许小范围试错和回滚。",
    type: "scale",
    sortOrder: 52,
  },
  {
    id: "chain_4",
    module: "chain",
    title: "我们能写清人、AI、自动化分别负责什么。",
    type: "scale",
    sortOrder: 53,
  },
  {
    id: "chain_5",
    module: "chain",
    title: "这条工作流跑完后能沉淀模板、清单、提示词、接口或复盘记录。",
    type: "scale",
    sortOrder: 54,
  },

  {
    id: "charter_1",
    module: "charter",
    title: "我们知道哪些场景可以使用 AI，哪些场景不能使用 AI。",
    type: "scale",
    sortOrder: 60,
  },
  {
    id: "charter_2",
    module: "charter",
    title: "我们知道哪些 AI 输出必须人工确认。",
    type: "scale",
    sortOrder: 61,
  },
  {
    id: "charter_3",
    module: "charter",
    title: "AI 影响招聘、绩效、薪酬、发展机会等场景时，有明确责任主体。",
    type: "scale",
    sortOrder: 62,
  },
  {
    id: "charter_4",
    module: "charter",
    title: "我们知道哪些数据不能进入外部模型或未经授权的工具。",
    type: "scale",
    sortOrder: 63,
  },
  {
    id: "charter_5",
    module: "charter",
    title: "员工或客户可以质疑、申诉或要求解释 AI 相关决定。",
    type: "scale",
    sortOrder: 64,
  },

  {
    id: "open_scenario",
    module: "open",
    title: "请写下一个真实场景：AI 确实提高了某些人的效率，但组织并没有真的变强。",
    description: "请避免公司敏感信息，写清角色、场景和卡点即可。",
    type: "text",
    sortOrder: 80,
  },
  {
    id: "open_workflow",
    module: "open",
    title: "如果只能选择一条工作流做 AI 化试点，你最想选哪一条？为什么？",
    type: "text",
    sortOrder: 81,
  },
  {
    id: "open_blocker",
    module: "open",
    title: "在你的组织里，AI 转型最大的阻力更像来自意义、权力还是信任？请写一个具体例子。",
    type: "text",
    sortOrder: 82,
  },
];

export const moduleMeta = {
  stage: {
    title: "AI 转型五级阶梯",
    description: "判断组织当前真实处于哪一层，而不是停留在哪一种口号。",
  },
  spiral: {
    title: "三螺旋组织诊断",
    description: "识别结构层、细胞层和环境层的主要卡点。",
  },
  energy: {
    title: "意义、权力、信任",
    description: "看见 AI 转型背后的组织暗流。",
  },
  chain: {
    title: "人机链路准备度",
    description: "判断是否具备启动一条真实工作流实验的基础。",
  },
  charter: {
    title: "AI 宪章准备度",
    description: "检查边界、责任、复核和申诉机制是否清晰。",
  },
  open: {
    title: "真实案例采集",
    description: "把组织现场带入工作坊讨论。",
  },
} as const;

export const orderedModules = ["stage", "spiral", "energy", "chain", "charter", "open"] as const;
